# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rothko Me
description: The Sass experiment that Mark Rothko dreamt of
baseurl: "" # the subpath of your site, e.g. /blog
keywords: rothko, interactive, art, swag, sass, colour field, color field, abstract expressionism
url: "http://rothko.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /404.html
sass:
    style: compressed
